import globals from 'globals';
import html from 'eslint-plugin-html';
import prettier from 'eslint-config-prettier';

export default [
    {
        ignores: ['eslint.config.js', 'node_modules/**'],
    },
    {
        files: ['js/**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'script',
            globals: {
                ...globals.browser,
                firebase: 'readonly',
                // constants.js globals
                BOARD_SIZE: 'readonly',
                STORAGE_SIZE: 'readonly',
                SHOP_SIZE: 'readonly',
                SHOP_REFRESH_MS: 'readonly',
                MAX_ENERGY: 'readonly',
                RECOVERY_SEC: 'readonly',
                UNLOCK_COST_BOARD: 'readonly',
                ENERGY_COST: 'readonly',
                CAGE_UPGRADE_COST: 'readonly',
                CAGE_MAX_LEVEL: 'readonly',
                GRID_COLS: 'readonly',
                GRID_ROWS: 'readonly',
                // 주사위 여행 상수
                DICE_TRIP_SIZE: 'readonly',
                DICE_DROP_CHANCE: 'readonly',
                DICE_TRIP_COMPLETE_REWARD: 'readonly',
                SPECIAL_CAGE_MAX_LEVEL: 'readonly',
                DICE_TRIP_REWARDS: 'readonly',
                SPECIAL_CAGE_SPAWNS: 'readonly',
                CATS: 'readonly',
                DOGS: 'readonly',
                BIRDS: 'readonly',
                FISH: 'readonly',
                REPTILES: 'readonly',
                CAT_SNACKS: 'readonly',
                DOG_SNACKS: 'readonly',
                CAT_TOYS: 'readonly',
                DOG_TOYS: 'readonly',
                NPC_AVATARS: 'readonly',
                DAILY_MISSIONS: 'readonly',
                DAILY_COMPLETE_REWARD: 'readonly',
                SNACK_CHANCE: 'readonly',
                ALBUM_THEMES: 'readonly',
                ALBUM_CARD_COST: 'readonly',
                ALBUM_DRAW_COUNT: 'readonly',
                ALBUM_CARD_CHANCE: 'readonly',
                ALBUM_CARD_MIN: 'readonly',
                ALBUM_CARD_MAX: 'readonly',
                ALBUM_DUPE_REWARD: 'readonly',
                ALBUM_COMPLETE_COINS: 'readonly',
                ALBUM_ALL_COMPLETE_DIAMONDS: 'readonly',
                ALBUM_CYCLE_MS: 'readonly',
                ATTENDANCE_REWARDS: 'readonly',
                getItemData: 'readonly',
                getMaxLevel: 'readonly',
                getItemList: 'readonly',
                getGeneratorName: 'readonly',
                getSpecialTypeName: 'readonly',
                getKSTDateString: 'readonly',
                getMsUntilKSTMidnight: 'readonly',
                // state.js globals (writable - shared state)
                boardState: 'writable',
                storageState: 'writable',
                shopItems: 'writable',
                coins: 'writable',
                cumulativeCoins: 'writable',
                diamonds: 'writable',
                // 주사위 여행 변수
                diceTripPosition: 'writable',
                diceCount: 'writable',
                isRollingDice: 'writable',
                specialCageLevel: 'writable',
                diceTripContainer: 'writable',
                diceTripBoard: 'writable',
                energy: 'writable',
                recoveryCountdown: 'writable',
                userLevel: 'writable',
                questProgress: 'writable',
                quests: 'writable',
                questIdCounter: 'writable',
                questPage: 'writable',
                prevReadyCount: 'writable',
                totalQuestsCompleted: 'writable',
                genLevels: 'writable',
                dragData: 'writable',
                currentGuideType: 'writable',
                currentGuideTab: 'writable',
                sellTarget: 'writable',
                shopNextRefresh: 'writable',
                discoveredItems: 'writable',
                newlyDiscoveredItems: 'readonly',
                specialMissionCycles: 'writable',
                isTutorialActive: 'writable',
                dailyMissions: 'writable',
                energyPurchaseCount: 'writable',
                energyPurchaseResetTime: 'writable',
                firstEnergyRewardGiven: 'writable',
                cloudSaveTimeout: 'writable',
                cloudSavePromise: 'writable',
                pendingCloudData: 'writable',
                energyPopupTimer: 'writable',
                currentUser: 'writable',
                currentSessionId: 'writable',
                sessionUnsubscribe: 'writable',
                boardEl: 'writable',
                storageEl: 'writable',
                shopGrid: 'writable',
                coinEl: 'writable',
                diamondEl: 'writable',
                energyEl: 'writable',
                energyTimerEl: 'writable',
                levelEl: 'writable',
                questContainer: 'writable',
                dailyMissionsContainer: 'writable',
                dailyResetTimer: 'writable',
                shopTimerBadge: 'writable',
                tutorialPointer: 'writable',
                // state.js - album
                cards: 'writable',
                album: 'writable',
                currentAlbumTheme: 'writable',
                albumResetTime: 'writable',
                lastDailyBonusDate: 'writable',
                loginStreak: 'writable',
                // state.js - race
                currentRaceId: 'writable',
                myRaceCode: 'writable',
                raceWins: 'writable',
                raceLosses: 'writable',
                raceUnsubscribe: 'writable',
                recentRaceOpponents: 'writable',
                pendingInviteId: 'writable',
                pendingInviteData: 'writable',
                inviteTimerInterval: 'writable',
                // auth.js globals
                auth: 'readonly',
                db: 'readonly',
                googleProvider: 'readonly',
                generateSessionId: 'readonly',
                registerSession: 'readonly',
                startSessionListener: 'readonly',
                stopSessionListener: 'readonly',
                startGoogleLogin: 'readonly',
                handleGoogleLogin: 'readonly',
                showLoginScreen: 'readonly',
                showGameScreen: 'readonly',
                // save.js globals
                getGameData: 'readonly',
                applyGameData: 'readonly',
                migrateRow7Missions: 'readonly',
                saveGame: 'readonly',
                saveGameNow: 'readonly',
                updateSaveStatus: 'readonly',
                sanitizeForFirestore: 'readonly',
                isValidSaveData: 'readonly',
                saveToCloud: 'readonly',
                loadFromCloud: 'readonly',
                validateGameData: 'readonly',
                initNewGame: 'readonly',
                // game.js globals
                discoverItem: 'readonly',
                countEasyQuests: 'readonly',
                generateNewQuest: 'readonly',
                scrollQuests: 'readonly',
                completeQuest: 'readonly',
                checkExpiredQuests: 'readonly',
                formatQuestTimer: 'readonly',
                spawnItem: 'readonly',
                spawnToy: 'readonly',
                handleCellClick: 'readonly',
                triggerGen: 'readonly',
                getEnergyPrice: 'readonly',
                checkEnergyAfterUse: 'readonly',
                openEnergyPopup: 'readonly',
                closeEnergyPopup: 'readonly',
                buyEnergy: 'readonly',
                getActiveTypes: 'readonly',
                checkToyGeneratorUnlock: 'readonly',
                moveItem: 'readonly',
                checkDailyBonus: 'readonly',
                checkDailyReset: 'readonly',
                addDailyProgress: 'readonly',
                checkDailyMissionComplete: 'readonly',
                claimDailyBonus: 'readonly',
                // systems.js globals
                getSlotUnlockLevel: 'readonly',
                updateSpecialMissionUI: 'readonly',
                updateSlot: 'readonly',
                spawnSpecialGenerator: 'readonly',
                completeSpecialMission: 'readonly',
                checkAutoCompleteMissions: 'readonly',
                startShopTimer: 'readonly',
                refreshShop: 'readonly',
                generateRandomShopItem: 'readonly',
                renderShop: 'readonly',
                buyShopItem: 'readonly',
                askSellItem: 'readonly',
                // 주사위 여행 함수
                tryDropDice: 'readonly',
                useDice: 'readonly',
                rollDice: 'readonly',
                moveTripPosition: 'readonly',
                giveStepReward: 'readonly',
                completeTrip: 'readonly',
                spawnSpecialCage: 'readonly',
                handleSpecialCageClick: 'readonly',
                updateDiceTripUI: 'readonly',
                renderDiceTripBoard: 'readonly',
                // album.js globals
                getRandomPhoto: 'readonly',
                processDrawResult: 'readonly',
                drawPhotos: 'readonly',
                openPhotoDraw: 'readonly',
                closePhotoDraw: 'readonly',
                openAlbum: 'readonly',
                closeAlbum: 'readonly',
                renderAlbumTabs: 'readonly',
                switchAlbumTheme: 'readonly',
                renderAlbumGrid: 'readonly',
                checkThemeComplete: 'readonly',
                getAlbumProgress: 'readonly',
                getCompletedThemes: 'readonly',
                formatAlbumTimer: 'readonly',
                checkAlbumReset: 'readonly',
                checkAlbumAllComplete: 'readonly',
                updateAlbumBarUI: 'readonly',
                // race.js globals
                RACE_GOAL: 'readonly',
                RACE_REWARDS: 'readonly',
                RACE_INVITE_EXPIRE_MS: 'readonly',
                generateRaceCode: 'readonly',
                getOrCreateMyCode: 'readonly',
                findActiveRace: 'readonly',
                findActiveOrPendingRace: 'readonly',
                startPlayer2Listener: 'readonly',
                stopPlayer2Listener: 'readonly',
                joinRaceByCode: 'readonly',
                copyRaceCode: 'readonly',
                startRaceListener: 'readonly',
                stopRaceListener: 'readonly',
                updateRaceProgress: 'readonly',
                checkRaceWinner: 'readonly',
                showRaceResult: 'readonly',
                claimRaceReward: 'readonly',
                addRecentOpponent: 'readonly',
                quickJoinRace: 'readonly',
                updateRaceUI: 'readonly',
                updateRaceUIFromData: 'readonly',
                openRaceJoinPopup: 'readonly',
                submitRaceCode: 'readonly',
                validateCurrentRace: 'readonly',
                initRace: 'readonly',
                showRaceInvitePopup: 'readonly',
                closeRaceInvitePopup: 'readonly',
                startInviteTimer: 'readonly',
                stopInviteTimer: 'readonly',
                acceptRaceInvite: 'readonly',
                declineRaceInvite: 'readonly',
                cancelPendingInvite: 'readonly',
                expireInvite: 'readonly',
                updatePendingInviteUI: 'readonly',
                // ui.js globals
                renderGrid: 'readonly',
                createItem: 'readonly',
                updateAll: 'readonly',
                updateUI: 'readonly',
                updateLevelupProgressUI: 'readonly',
                updateTimerUI: 'readonly',
                updateQuestUI: 'readonly',
                spawnParticles: 'readonly',
                spawnItemEffect: 'readonly',
                showLuckyEffect: 'readonly',
                showFloatText: 'readonly',
                showToast: 'readonly',
                showMilestonePopup: 'readonly',
                closeOverlay: 'readonly',
                formatTime: 'readonly',
                updateEnergyPopupTimer: 'readonly',
                handleDragStart: 'readonly',
                handleDragMove: 'readonly',
                handleDragEnd: 'readonly',
                openGuide: 'readonly',
                closeModal: 'readonly',
                switchGuideTab: 'readonly',
                renderGuideList: 'readonly',
                updateUpgradeUI: 'readonly',
                upgradeGenerator: 'readonly',
                updateDailyMissionUI: 'readonly',
                startDailyMissionTimer: 'readonly',
            },
        },
        rules: {
            'no-unused-vars': 'off',
            'no-var': 'warn',
            'prefer-const': 'warn',
            eqeqeq: ['warn', 'always'],
            'no-console': 'off',
        },
    },
    {
        files: ['**/*.html'],
        plugins: { html },
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'script',
            globals: {
                ...globals.browser,
                firebase: 'readonly',
                // constants.js globals
                BOARD_SIZE: 'readonly',
                STORAGE_SIZE: 'readonly',
                APARTMENT_ROOMS: 'readonly',
                SHOP_SIZE: 'readonly',
                SHOP_REFRESH_MS: 'readonly',
                MAX_ENERGY: 'readonly',
                RECOVERY_SEC: 'readonly',
                UNLOCK_COST_BOARD: 'readonly',
                ENERGY_COST: 'readonly',
                CAGE_UPGRADE_COST: 'readonly',
                CAGE_MAX_LEVEL: 'readonly',
                FIRE_EXTINGUISH_COST: 'readonly',
                RESCUE_QUEST_REWARD: 'readonly',
                FIRE_EXTINGUISH_REWARD: 'readonly',
                SPECIAL_QUEST_GOAL: 'readonly',
                SPECIAL_QUEST_STEP: 'readonly',
                GRID_COLS: 'readonly',
                GRID_ROWS: 'readonly',
                CATS: 'readonly',
                DOGS: 'readonly',
                BIRDS: 'readonly',
                FISH: 'readonly',
                REPTILES: 'readonly',
                CAT_SNACKS: 'readonly',
                DOG_SNACKS: 'readonly',
                CAT_TOYS: 'readonly',
                DOG_TOYS: 'readonly',
                NPC_AVATARS: 'readonly',
                PM_GOALS: 'readonly',
                ROULETTE_SEGMENTS: 'readonly',
                QUEST_BASE_REWARD: 'readonly',
                QUEST_MULTIPLIERS: 'readonly',
                SNACK_CHANCE: 'readonly',
                TOY_CHANCE: 'readonly',
                getItemData: 'readonly',
                getMaxLevel: 'readonly',
                getItemLabel: 'readonly',
            },
        },
        rules: {
            // onclick 등 HTML 이벤트 핸들러에서 호출하는 함수는 false positive
            'no-unused-vars': [
                'warn',
                {
                    argsIgnorePattern: '^_',
                    varsIgnorePattern: '^(handle|start|close|scroll|complete|buy|upgrade|open|toggle|sell|show)',
                },
            ],
            'no-var': 'warn',
            'prefer-const': 'warn',
            eqeqeq: ['warn', 'always'],
            'no-console': 'off',
        },
    },
    prettier,
];
